In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'3.0.2'

In [3]:
columns = ['A', 'B', 'C', 'D'] # titles
columns

['A', 'B', 'C', 'D']

In [4]:
data = np.array([[1, 2, -1, 0], [3, -1, 2, 5], [-1, 4, 0, 2], [-1, -2, 3, 0]])
data

array([[ 1,  2, -1,  0],
       [ 3, -1,  2,  5],
       [-1,  4,  0,  2],
       [-1, -2,  3,  0]])

In [5]:
df = pd.DataFrame(data=data, columns=columns)

In [6]:
df

   A  B  C  D
0  1  2 -1  0
1  3 -1  2  5
2 -1  4  0  2
3 -1 -2  3  0

In [7]:
df['A']

0    1
1    3
2   -1
3   -1
Name: A, dtype: int64

In [8]:
df[['A', 'C']]

   A  C
0  1 -1
1  3  2
2 -1  0
3 -1  3

In [9]:
df[['A', 'C']]['A']

0    1
1    3
2   -1
3   -1
Name: A, dtype: int64

In [10]:
df['E'] = df['A'] + df['B']
df

   A  B  C  D  E
0  1  2 -1  0  3
1  3 -1  2  5  2
2 -1  4  0  2  3
3 -1 -2  3  0 -3

In [11]:
df[df > 0]

     A    B    C    D    E
0  1.0  2.0  NaN  NaN  3.0
1  3.0  NaN  2.0  5.0  2.0
2  NaN  4.0  NaN  2.0  3.0
3  NaN  NaN  3.0  NaN  NaN

In [12]:
df[ df > 2 ]['E']

0    3.0
1    NaN
2    3.0
3    NaN
Name: E, dtype: float64